// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('pressSendButton', function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  // Непосредственно тест
  it('pressSendButton', async function () {
    // Переход по ссылке
    await driver.get("http://127.0.0.1:5500/index.html")
    await driver.manage().window().setRect(968, 1029)
    // Ввод строки
    await driver.findElement(By.id("text-input")).click()
    await driver.findElement(By.id("text-input")).sendKeys("String")
    // Нажатие на кнопку
    await driver.findElement(By.css("input:nth-child(3)")).click();
    await driver.quit();
  })
})
